config/routes.rb
Property3::Application.routes.draw do

  resources :houses do
    collection do
      match 'search' => 'houses#search', via: [:get, :post], as: :search
    end
  end

get :controller => "houses", :action => 'jsonindex'

  root :to => 'houses#index' 

    

  

end

app/models/house.rb
class House < ActiveRecord::Base
	validates_presence_of :location, :price, :beds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  respond_to :json, :html, :jpg, :xml

  # GET /houses
  # GET /houses.json
  #def index
    #@houses = House.all
  #end



def index
   #@search = House.search(params[:q])
   #@houses = @search.result

  @q = House.search(params[:q])
  @houses = @q.result(distinct: true)

#@houses = House.all
#render :json => @houses.to_json
end

def jsonindex
   #@search = House.search(params[:q])
   #@houses = @search.result

  #@q = House.search(params[:q])
  #@houses = @q.result(distinct: true)

  @houses = House.all
  render :json => @houses.to_json
end


def search
  index
  render :index
end



  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render action: 'show', status: :created, location: @house }
      else
        format.html { render action: 'new' }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:location, :price, :beds)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
<!--

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :beds %><br>
    <%= f.number_field :beds %>
  </div>

-->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h1>PROPERTYflow<h1>

<hr>

<h3> <%= link_to 'Complete property list:', houses_path %> </h3> 

<style> 


.sorting
{
transform:rotate(6deg);
-ms-transform:rotate(6deg); /* IE 9 */
-webkit-transform:rotate(6deg); /* Safari and Chrome */

position:absolute;
left:800px;
top:275px;
}
.table
{
position:absolute;
left:20px;
top:100px;
}


h1
{
color:white;
font-size:300%;
text-align:center;
font-size: 20;
position:absolute;
left:450px;
top:5px;
}
h3
{
color:red;
position:absolute;
left:440px;
top:200px;
}
</style>

<div  class="table">
<%= search_form_for @q do |f| %>
  <%= f.label "Location" %>
  <%= f.text_field :location_cont %>
  <br>  
  <!-- <%= f.label :beds_cont %>
  <%= f.text_field :beds_cont %>
  <br>  
  <%= f.label :price_cont %>
  <%= f.text_field :price_cont %>
-->
  <br>  
  <%= f.submit %>
<% end %>
</div>


<br> 


  <%= search_form_for @q, url: search_houses_path, html: { method: :post } do |f| %>
    <%= f.condition_fields do |c| %>
    <%= render "condition_fields", f: c %>
  <% end %>


<div class="sorting">
<table id="houses">
  <tr>
    <th><%= sort_link @q, :location, "Location" %></th>
    <th><%= sort_link @q, :beds, "Beds" %></th>
    <th><%= sort_link @q, :price, "Price" %></th>
  </tr>
<% @houses.each do |houses| %>
  <tr>
    <td><%= link_to(houses.location, houses) %></td>
    <td><%= houses.beds %></td>
    <td><%= number_to_currency(houses.price) %></td>
  </tr>
<% end %>
</table>
</div>
 
<br> 

<% end %>

<br>

<!-- <%= link_to 'New Property', new_house_path %> -->
<h2> <%= link_to "( A JSON response link: )", {:controller => 'houses', :action => 'jsonindex'} %> </h2>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @house.location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @house.price %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @house.beds %>
</p>

<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Property3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body style="background-color:LightBlue">

<%= yield %>

</body>
</html>